services:
  sensor1:
    build: .
    environment:
      - SENSOR_NAME=sensor1
    env_file:
      - .env
    networks:
      - sensors_network

  sensor2:
    build: .
    environment:
      - SENSOR_NAME=sensor2
    env_file:
      - .env  
    networks:
      - sensors_network

  sensor3:
    build: .
    environment:
      - SENSOR_NAME=sensor3
    env_file:
      - .env
    networks:
      - sensors_network

  sensor4:
    build: .
    environment:
      - SENSOR_NAME=sensor4
    env_file:
      - .env
    networks:
      - sensors_network

  sensor5:
    build: .
    environment:
      - SENSOR_NAME=sensor5
    env_file:
      - .env
    networks:
      - sensors_network

networks:
  sensors_network:
    driver: bridge